packages:
  - 'apps/*'
  - 'packages/*'
  - 'infrastructure'
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@tailwindcss/oxide'
  - esbuild
  - core-js-pure
allowBuilds:
  sharp: true
  unrs-resolver: true
  '@tailwindcss/oxide': true
  esbuild: true
  core-js-pure: true
minimumReleaseAgeExclude:
  - '@storybook/builder-webpack5@10.4.3'
  - '@storybook/core-webpack@10.4.3'
  - '@storybook/nextjs@10.4.3'
  - '@storybook/preset-react-webpack@10.4.3'
  - '@storybook/react-dom-shim@10.4.3'
  - '@storybook/react@10.4.3'
  - storybook@10.4.3
